common:

  subject_prefix_for_outgoing_emails: WHEEL
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  honeybadger_api_key: <%= ENV['HONEYBADGER_API_KEY'] %>
  host: <%= ENV['APP_URL'] || ENV['HEROKU_URL'] || 'http://localhost:3000' %>

  twilio:
    from_number: <%= ENV['TWILIO_FROM_NUMBER'] %>
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>

  aws_s3:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>

  mailer:
    default_from_email: "'Wheel' <notifications@wheel.com>"
    delivery_method: test
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain

  support_email:
    support@example.com

  devise:
    secret_key: <%= ENV['DEVISE_KEY'] || SecureRandom.hex(64) %>

development:
  mailer:
    delivery_method: :smtp
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com

test:
  mailer:
    delivery_method: :test
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com

staging:
  mailer:
    delivery_method: :smtp

    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: www.wheel.com
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true

  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com
  support_email:
    support@example.com

production:
  bcc: hello.wheel@gmail.com
  mailer:
    delivery_method: :smtp

    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: www.wheel.com
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true

  support_email:
    support@example.com
